development:
  adapter: mysql2
  database: records_development
  username: root
  password: 705015MK
  host: localhost

test:
  adapter: mysql2
  database: records_test
  username: root
  password: 705015MK
  host: localhost
